DigitalMusicLibrary/Controllers/AddMusicDetailController.cs
using DigitalMusicLibrary.Filters;
using DigitalMusicLibrary.Models.DataModels;
using DigitalMusicLibrary.Models.ViewModels;
using DigitalMusicLibrary.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using System.Web.Mvc;

namespace DigitalMusicLibrary.Controllers
{
    [AdminRoleValidateFilter]
    public class AddMusicDetailController : Controller
    {
        private IMusicRepository<MusicDetail> repository = null;
        public AddMusicDetailController()
        {
            this.repository = new MusicRepository<MusicDetail>();
        }
        public AddMusicDetailController(IMusicRepository<MusicDetail> repository)
        {
            this.repository = repository;
        }


        public ActionResult Index()
        {
            return View();
        }

        public ActionResult UploadMusicDetais()
        {
            return View(new AddMusicViewModel());
        }

        [HttpPost]
        public ActionResult UploadMusicDetais(AddMusicViewModel viewModel, HttpPostedFileBase uploadFile)
        {
            if (!string.IsNullOrEmpty(uploadFile?.FileName))
            {
                var musicDetail = new MusicDetail
                {
                    AlbuName = viewModel.AlbuName,
                    ArtistName = viewModel.ArtistName,
                    ComposerName = viewModel.ComposerName,
                    FileName = uploadFile.FileName,
                    ReleasedDate = viewModel.ReleasedDate,
                    TitleName = viewModel.TitleName
                };

                using (var reader = new System.IO.BinaryReader(uploadFile.InputStream))
                {
                    musicDetail.File = reader.ReadBytes(uploadFile.ContentLength);
                }

                repository.Insert(musicDetail);
                repository.Save();

            }
            else
            {
                ModelState.AddModelError("", "Please upload a file");
                return View(viewModel);
            }
            return View("Index");
        }
    }
}

DigitalMusicLibrary/Views/AddMusicDetail/Index.cshtml
@{
    ViewBag.Title = "Index";
}



@Html.ActionLink("Add New Music", "UploadMusicDetais", "AddMusicDetail")

DigitalMusicLibrary/Views/AddMusicDetail/UploadMusicDetais.cshtml
@model DigitalMusicLibrary.Models.ViewModels.AddMusicViewModel

@{
    ViewBag.Title = "Upload Music Detais";
}

<h2>Upload Music Detais</h2>


@using (Html.BeginForm("UploadMusicDetais", "AddMusicDetail", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Add Music </h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.TitleName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TitleName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TitleName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AlbuName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AlbuName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AlbuName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ComposerName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ComposerName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ComposerName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ArtistName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ArtistName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ArtistName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ReleasedDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ReleasedDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ReleasedDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("File", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" id="UploadFile" name="uploadFile" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}